name: CI

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'chore/**'
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '6.1'

      - name: Install SwiftLint
        run: |
          brew install swiftlint

      - name: Lint
        run: swiftlint --strict

      - name: Format Check
        run: swift format lint --configuration .swift-format.json --recursive .

      # Swift 6.3などにするまでビルドテストはコメントアウト
      # - name: Swift Build
      #   run: swift build

      - name: Swift Test
        run: swift test

      - name: Xcodebuild Tests
        run: xcodebuild test -scheme SmallLight-Package -destination 'platform=macOS'
