name: CI

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'chore/**'
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # swift-actions/setup-swift does not support Swift 6.2 yet; install toolchain manually.
      - name: Install Swift 6.2 toolchain
        run: |
          SWIFT_URL="https://download.swift.org/swift-6.2-release/xcode/swift-6.2-RELEASE/swift-6.2-RELEASE-osx.pkg"
          curl -L "$SWIFT_URL" -o swift-toolchain.pkg
          sudo installer -pkg swift-toolchain.pkg -target /
          rm swift-toolchain.pkg

      - name: Configure Swift toolchain
        run: |
          TOOLCHAIN_ROOT="/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain"
          sudo xcode-select -switch /Applications/Xcode.app
          echo "${TOOLCHAIN_ROOT}/usr/bin" >> "$GITHUB_PATH"
          echo "TOOLCHAINS=swift" >> "$GITHUB_ENV"
          swift --version

      - name: Install SwiftLint
        run: |
          brew install swiftlint

      - name: Lint
        run: swiftlint --strict

      - name: Format Check
        run: swift format lint --configuration .swift-format.json --recursive .

      - name: Swift Build
        run: swift build

      - name: Swift Test
        run: swift test

      - name: Xcodebuild Tests
        run: xcodebuild test -scheme SmallLight-Package -destination 'platform=macOS'
