name: CI

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'chore/**'
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Swift 6.3 snapshot toolchain
        env:
          SWIFT_SNAPSHOT: swift-6.3-DEVELOPMENT-SNAPSHOT-2025-10-01-a
        run: |
          SNAPSHOT_DIR="swift-6.3-branch/xcode/${SWIFT_SNAPSHOT}"
          SWIFT_URL="https://download.swift.org/${SNAPSHOT_DIR}/${SWIFT_SNAPSHOT}-osx.pkg"
          curl -L "$SWIFT_URL" -o swift-toolchain.pkg
          sudo installer -pkg swift-toolchain.pkg -target /
          rm swift-toolchain.pkg

      - name: Configure Swift toolchain
        env:
          SWIFT_SNAPSHOT: swift-6.3-DEVELOPMENT-SNAPSHOT-2025-10-01-a
        run: |
          TOOLCHAIN_ROOT="/Library/Developer/Toolchains/${SWIFT_SNAPSHOT}.xctoolchain"
          sudo xcode-select -switch /Applications/Xcode.app
          echo "${TOOLCHAIN_ROOT}/usr/bin" >> "$GITHUB_PATH"
          echo "TOOLCHAINS=swift" >> "$GITHUB_ENV"
          swift --version

      - name: Install SwiftLint
        run: |
          brew install swiftlint

      - name: Lint
        run: swiftlint --strict

      - name: Format Check
        run: swift format lint --configuration .swift-format.json --recursive .

      - name: Swift Build
        run: swift build

      - name: Swift Test
        run: swift test

      - name: Xcodebuild Tests
        run: xcodebuild test -scheme SmallLight-Package -destination 'platform=macOS'
